import type {
  Attraction,
  CapacityData,
  Transaction,
  User,
} from './types';

export const AFORO_MAXIMO = 5000;

export const capacityData: CapacityData = {
  ingresosFisicos: 2450,
  ingresosApp: 890,
  aforoTotal: AFORO_MAXIMO,
};

export const users: User[] = [
  {
    id: 'U-001',
    nombre: 'Carolina Ramírez',
    categoria: 'A',
    puntos: 320,
    acompañantes: [
      { nombre: 'Mateo Ramírez', edad: 8 },
      { nombre: 'Sofía Ramírez', edad: 11 },
    ],
  },
  {
    id: 'U-002',
    nombre: 'Andrés Gutiérrez',
    categoria: 'A',
    puntos: 410,
    acompañantes: [{ nombre: 'Laura Gutiérrez', edad: 34 }],
  },
  {
    id: 'U-003',
    nombre: 'Valentina Torres',
    categoria: 'B',
    puntos: 210,
    acompañantes: [
      { nombre: 'Juan Torres', edad: 38 },
      { nombre: 'Isabela Torres', edad: 6 },
    ],
  },
  {
    id: 'U-004',
    nombre: 'Sebastián Herrera',
    categoria: 'B',
    puntos: 185,
    acompañantes: [],
  },
  {
    id: 'U-005',
    nombre: 'Daniela Ospina',
    categoria: 'C',
    puntos: 150,
    acompañantes: [
      { nombre: 'Martín Ospina', edad: 9 },
      { nombre: 'Gabriela Ospina', edad: 13 },
      { nombre: 'Camila Ospina', edad: 40 },
    ],
  },
  {
    id: 'U-006',
    nombre: 'Juan Pablo Mejía',
    categoria: 'C',
    puntos: 95,
    acompañantes: [{ nombre: 'Lucía Mejía', edad: 7 }],
  },
  {
    id: 'U-007',
    nombre: 'María José Castaño',
    categoria: 'None',
    puntos: 0,
    acompañantes: [],
  },
  {
    id: 'U-008',
    nombre: 'Felipe Aguirre',
    categoria: 'None',
    puntos: 0,
    acompañantes: [{ nombre: 'Natalia Aguirre', edad: 29 }],
  },
  {
    id: 'U-009',
    nombre: 'Laura Betancur',
    categoria: 'A',
    puntos: 275,
    acompañantes: [
      { nombre: 'Samuel Betancur', edad: 10 },
      { nombre: 'Santiago Betancur', edad: 5 },
    ],
  },
  {
    id: 'U-010',
    nombre: 'Diego Hernández',
    categoria: 'B',
    puntos: 160,
    acompañantes: [{ nombre: 'Ana Hernández', edad: 36 }],
  },
];

export const attractions: Attraction[] = [
  {
    id: 'ATR-001',
    nombre: 'Tobogán Kamikaze',
    reservable: true,
    capacidadTurno: 40,
    usuariosEnFila: 28,
    cooldownMinutos: 90,
    estado: 'abierta',
  },
  {
    id: 'ATR-002',
    nombre: 'Río Lento',
    reservable: true,
    capacidadTurno: 120,
    usuariosEnFila: 75,
    cooldownMinutos: 60,
    estado: 'abierta',
  },
  {
    id: 'ATR-003',
    nombre: 'Montaña Rusa Acuática',
    reservable: true,
    capacidadTurno: 32,
    usuariosEnFila: 40,
    cooldownMinutos: 120,
    estado: 'abierta',
  },
  {
    id: 'ATR-004',
    nombre: 'Toboganes Gigantes',
    reservable: true,
    capacidadTurno: 60,
    usuariosEnFila: 22,
    cooldownMinutos: 75,
    estado: 'mantenimiento',
  },
  {
    id: 'ATR-005',
    nombre: 'Splash Tower',
    reservable: true,
    capacidadTurno: 45,
    usuariosEnFila: 35,
    cooldownMinutos: 90,
    estado: 'abierta',
  },
  {
    id: 'ATR-006',
    nombre: 'Olas del Pacífico',
    reservable: true,
    capacidadTurno: 150,
    usuariosEnFila: 110,
    cooldownMinutos: 45,
    estado: 'abierta',
  },
  {
    id: 'ATR-007',
    nombre: 'Laberinto Acuático',
    reservable: true,
    capacidadTurno: 50,
    usuariosEnFila: 18,
    cooldownMinutos: 60,
    estado: 'abierta',
  },
  {
    id: 'POI-001',
    nombre: 'Piscina Olímpica',
    reservable: false,
    capacidadTurno: 200,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-002',
    nombre: 'Piscina Infantil',
    reservable: false,
    capacidadTurno: 150,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-003',
    nombre: 'Piscina de Olas',
    reservable: false,
    capacidadTurno: 300,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-004',
    nombre: 'Piscina Semi-Olímpica',
    reservable: false,
    capacidadTurno: 180,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-005',
    nombre: 'Jacuzzi Familiar',
    reservable: false,
    capacidadTurno: 25,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-006',
    nombre: 'Restaurante Central',
    reservable: false,
    capacidadTurno: 180,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-007',
    nombre: 'Restaurante La Palma',
    reservable: false,
    capacidadTurno: 120,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-008',
    nombre: 'Pizzería del Parque',
    reservable: false,
    capacidadTurno: 90,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-009',
    nombre: 'Heladería Tropical',
    reservable: false,
    capacidadTurno: 60,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-010',
    nombre: 'Cafetería Express',
    reservable: false,
    capacidadTurno: 70,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-011',
    nombre: 'Zona de Comidas Rápidas',
    reservable: false,
    capacidadTurno: 220,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-012',
    nombre: 'Bar Tiki',
    reservable: false,
    capacidadTurno: 80,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-013',
    nombre: 'Zona de Picnic Norte',
    reservable: false,
    capacidadTurno: 150,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-014',
    nombre: 'Zona de Picnic Sur',
    reservable: false,
    capacidadTurno: 150,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-015',
    nombre: 'Canchas Deportivas',
    reservable: false,
    capacidadTurno: 60,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-016',
    nombre: 'Parque Infantil',
    reservable: false,
    capacidadTurno: 100,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-017',
    nombre: 'Mirador Panorámico',
    reservable: false,
    capacidadTurno: 40,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-018',
    nombre: 'Tienda de Recuerdos',
    reservable: false,
    capacidadTurno: 50,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-019',
    nombre: 'Locker Principal',
    reservable: false,
    capacidadTurno: 300,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
  {
    id: 'POI-020',
    nombre: 'Enfermería',
    reservable: false,
    capacidadTurno: 15,
    usuariosEnFila: 0,
    cooldownMinutos: 0,
    estado: 'abierta',
  },
];

export const transactions: Transaction[] = [
  {
    id: 'TX-001',
    userId: 'U-001',
    attractionId: 'ATR-001',
    turno: '10:30',
    timestamp: 1713350400000,
    tipo: 'FastPass',
  },
  {
    id: 'TX-002',
    userId: 'U-003',
    attractionId: 'ATR-003',
    turno: '11:00',
    timestamp: 1713352200000,
    tipo: 'FastPass',
  },
  {
    id: 'TX-003',
    userId: 'U-005',
    attractionId: 'ATR-006',
    turno: '11:30',
    timestamp: 1713354000000,
    tipo: 'FastPass',
  },
  {
    id: 'TX-004',
    userId: 'U-002',
    attractionId: 'POI-006',
    turno: '13:00',
    timestamp: 1713358800000,
    tipo: 'Comida',
  },
  {
    id: 'TX-005',
    userId: 'U-009',
    attractionId: 'ATR-005',
    turno: '12:15',
    timestamp: 1713356700000,
    tipo: 'FastPass',
  },
];

export function getGlobalCapacity(): number {
  return capacityData.ingresosFisicos + capacityData.ingresosApp;
}
